# Generated by Django 3.2.5 on 2021-08-02 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentData_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('percentage', models.FloatField()),
                ('standard', models.IntegerField()),
            ],
            options={
                'db_table': 'StudentData',
            },
        ),
    ]
