# Generated by Django 3.2.5 on 2021-08-02 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentData_Model',
            new_name='StudentData',
        ),
    ]
